//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDataEntities : DbContext
    {
        public MyDataEntities()
            : base("name=MyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblChucNang> tblChucNangs { get; set; }
        public virtual DbSet<tblComment> tblComments { get; set; }
        public virtual DbSet<tblDienThoai> tblDienThoais { get; set; }
        public virtual DbSet<tblDongDH> tblDongDHs { get; set; }
        public virtual DbSet<tblDonHang> tblDonHangs { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblLienHe> tblLienHes { get; set; }
        public virtual DbSet<tblNCC> tblNCCs { get; set; }
        public virtual DbSet<tblNguoiBan> tblNguoiBans { get; set; }
        public virtual DbSet<tblNguoiSuDung> tblNguoiSuDungs { get; set; }
        public virtual DbSet<tblNSX> tblNSXes { get; set; }
        public virtual DbSet<tblPhieuNhap> tblPhieuNhaps { get; set; }
        public virtual DbSet<tblPhieuXuat> tblPhieuXuats { get; set; }
        public virtual DbSet<tblQuyen> tblQuyens { get; set; }
        public virtual DbSet<tblDongPN> tblDongPNs { get; set; }
        public virtual DbSet<tblDongPX> tblDongPXes { get; set; }
        public virtual DbSet<tblLuotTruyCap> tblLuotTruyCaps { get; set; }
        public virtual DbSet<tblTemp> tblTemps { get; set; }
    }
}
