//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int CommentID { get; set; }
        public string IDDT { get; set; }
        public string TieuDe { get; set; }
        public string Comments { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    }
}
