//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDongDH
    {
        public int IDDonHang { get; set; }
        public string IDDT { get; set; }
        public Nullable<int> SLMua { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual tblDienThoai tblDienThoai { get; set; }
        public virtual tblDonHang tblDonHang { get; set; }
    }
}
