//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDienThoai()
        {
            this.tblDongDHs = new HashSet<tblDongDH>();
        }
    
        public string IDDT { get; set; }
        public int IDNSX { get; set; }
        public string TenDT { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string KichThuoc { get; set; }
        public string TrongLuong { get; set; }
        public string Camera { get; set; }
        public Nullable<byte> TheNho { get; set; }
        public Nullable<byte> CongNghe3G { get; set; }
        public Nullable<byte> Wifi { get; set; }
        public Nullable<byte> Java { get; set; }
        public string Pin { get; set; }
        public string ThoiGianCho { get; set; }
        public string ThoiGianDamThoai { get; set; }
        public string BaoHanh { get; set; }
        public string PhuKien { get; set; }
        public string HinhAnh { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> NCC { get; set; }
    
        public virtual tblNSX tblNSX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDongDH> tblDongDHs { get; set; }
    }
}
