//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNCC()
        {
            this.tblPhieuNhaps = new HashSet<tblPhieuNhap>();
        }
    
        public int IDNCC { get; set; }
        public string TenNCC { get; set; }
        public string GioiThieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuNhap> tblPhieuNhaps { get; set; }
    }
}
