//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuyen
    {
        public int ID { get; set; }
        public string TenDangNhap { get; set; }
        public int IDChucNang { get; set; }
        public string MoTa { get; set; }
        public string Page { get; set; }
        public Nullable<int> Macdinh { get; set; }
    
        public virtual tblChucNang tblChucNang { get; set; }
        public virtual tblNguoiSuDung tblNguoiSuDung { get; set; }
    }
}
